-- CREATE DATABASE customer_behavior; 

 SELECT *
FROM customer;

-- total rev generated by each gender
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- which customer used a discount but still spent more than avg purchase amt
SELECT customer_id, purchase_amount, discount_applied
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount > (
	SELECT AVG(purchase_amount) 
    FROM customer
)
;

-- top 5 products with highest review ratings
SELECT item_purchased, ROUND(AVG(review_rating),2) AS "avg_review_rating"
FROM customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5
;

-- avg purchase amt b/w standard and express shipping
SELECT shipping_type, ROUND(AVG(purchase_amount), 2)
FROM customer
GROUP BY shipping_type
HAVING shipping_type IN ("Express", "Standard")
;

-- avg spend and total revenue b/w subscribers and non subscribers to test whether subscription method working or not
SELECT subscription_status, COUNT(customer_id) AS "total_customers", SUM(purchase_amount) AS "total_revenue", AVG(purchase_amount) AS "avg_spend"
FROM customer
GROUP BY subscription_status
;

-- Which 5 products have highest % of purchases with discount applied shows which products rely on discount
--  eg 50% means out of 10 times of hats purchase, 5 hats are purchased when they were discounted
SELECT item_purchased,
ROUND((SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*))*100,2) AS "purchase_percentage"
FROM customer
GROUP BY item_purchased
ORDER BY purchase_percentage DESC
LIMIT 5
;


-- segment customers into new, returing, loyal based on their total previous purchases
SELECT CASE WHEN previous_purchases = 1 THEN "NEW"  WHEN previous_purchases BETWEEN 2 AND 10 THEN "RETURNING" ELSE "lOYAL" END AS "customer_type",
COUNT(customer_id)
FROM customer
GROUP BY customer_type
;

-- top 3 products in each category
WITH TOP_ITEMS_CTE AS(
SELECT category, item_purchased, COUNT(item_purchased) AS "sold_item_quantity",
	ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS "item_rank"
FROM customer
GROUP BY category, item_purchased
) 
SELECT *
FROM TOP_ITEMS_CTE
WHERE item_rank <= 3
;


-- are customers who are repeat buyers( more than 5 prev purchases) also likely to subscribe
SELECT subscription_status, COUNT(customer_id) AS "repeat_buyers"
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status
;


-- revenue contribution of each age group
SELECT age_group, SUM(purchase_amount)
FROM customer
GROUP BY age_group
;


SELECT category, SUM(purchase_amount), AVG(review_rating)
FROM customer
GROUP BY category